const types = {
  CREATE_SCHEDULE_REQUEST: 'CREATE_SCHEDULE_REQUEST',
  CREATE_SCHEDULE_SUCCESS: 'CREATE_SCHEDULE_SUCCESS',

  OPEN_MODAL_SUCCESS_CREATE_SCHEDULE: 'OPEN_MODAL_SUCCESS_CREATE_SCHEDULE',
  CLOSE_MODAL_SUCCESS_CREATE_SCHEDULE: 'CLOSE_MODAL_SIGN_OUT',
};

export default types;
